### ISSUE TITLE
hexo主题设置

### ISSUE THREAD

**Issue by Jabinzou** [yohnz/hexo-theme-card#2]
您好：我想请问一下你的文章缩略显示是怎么做的，我在这个icarus原文挡上找不着方法，请教一下

**Comment by yohnz** [comment]
在文章里需要的位置加一个标签，标签之前的便是缩略了

**Comment by yohnz** [comment]
@Jabinzou 在文章里需要的位置加一个标签，标签之前的便是缩略了
